"use client";

import Link from "next/link";
import { useState } from "react";
import { browserSupabase } from "@/lib/supabase/browser";
import HCaptchaField from "@/components/hcaptcha-field";

export default function AdminLoginPage() {
  const [error, setError] = useState(""); const [pending, setPending] = useState(false); const [captchaToken, setCaptchaToken] = useState("");
  async function login(form: FormData) { setPending(true); setError(""); const { error: authError } = await browserSupabase.auth.signInWithPassword({ email: String(form.get("email") ?? "").trim(), password: String(form.get("password") ?? ""), options: { captchaToken } }); setPending(false); if (authError) { setError("Email or password is incorrect."); setCaptchaToken(""); window.hcaptcha?.reset(); } else window.location.assign("/"); }
  return <main className="min-h-screen bg-[#f7fbff] px-5 py-10 text-[#10264a]"><div className="mx-auto max-w-sm"><p className="inline-flex items-center gap-2 text-sm font-extrabold text-[#2563eb]"><span className="grid size-8 place-items-center rounded-xl bg-[#2563eb] text-white">✦</span> BODY &amp; SOUL</p><p className="mt-12 text-xs font-extrabold uppercase tracking-[.16em] text-[#2563eb]">Secure dashboard</p><h1 className="mt-2 font-display text-3xl font-black tracking-[-.05em]">Super-admin sign in</h1><p className="mt-2 text-sm font-medium text-[#6980a5]">Use the private email and password you created during setup.</p><form action={login} className="mt-8 space-y-4 rounded-3xl border border-[#dceaff] bg-white p-5 shadow-[0_12px_35px_rgba(37,99,235,.06)]"><label className="block text-xs font-extrabold">Email address<input required autoComplete="email" className="mt-1.5 w-full rounded-xl border border-[#dceaff] px-3 py-3 text-sm font-medium outline-none focus:border-[#2563eb]" name="email" type="email" /></label><label className="block text-xs font-extrabold">Password<input required autoComplete="current-password" className="mt-1.5 w-full rounded-xl border border-[#dceaff] px-3 py-3 text-sm font-medium outline-none focus:border-[#2563eb]" name="password" type="password" /></label><HCaptchaField onToken={setCaptchaToken} />{error && <p className="rounded-xl bg-[#fff0f1] p-3 text-xs font-bold text-[#a83848]">{error}</p>}<button disabled={pending} className="w-full rounded-xl bg-[#2563eb] py-3 text-sm font-extrabold text-white disabled:opacity-60">{pending ? "Signing in…" : "Sign in"}</button></form><div className="mt-5 flex justify-between text-sm"><Link className="font-extrabold text-[#2563eb]" href="/admin/forgot-password">Forgot password?</Link><Link className="font-medium text-[#6980a5]" href="/member/login">Member sign in</Link></div><p className="mt-8 text-center text-xs text-[#6980a5]">First owner setup? <Link className="font-extrabold text-[#2563eb]" href="/admin/setup">Create super-admin account</Link></p></div></main>;
}
