"use client";

import { useActionState } from "react";
import { createSuperAdmin, type AdminFormState } from "@/app/admin/actions";

const initial: AdminFormState = {};
export default function AdminAccessForm() {
  const [state, action, pending] = useActionState(createSuperAdmin, initial);
  return <form action={action} className="rounded-3xl border border-[#dceaff] bg-white p-5 shadow-[0_12px_35px_rgba(37,99,235,.05)]"><h2 className="font-display text-xl font-black">Create super-admin</h2><p className="mt-1 text-sm font-medium text-[#6980a5]">Create a separate login, then give the email and initial password to that person securely. They get the same dashboard access as you.</p><label className="mt-5 block text-xs font-extrabold">Full name<input required maxLength={100} className="mt-1.5 w-full rounded-xl border border-[#dceaff] px-3 py-3 text-sm outline-none focus:border-[#2563eb]" name="full_name" placeholder="Harshdeep" /></label><label className="mt-4 block text-xs font-extrabold">Email address<input required maxLength={254} className="mt-1.5 w-full rounded-xl border border-[#dceaff] px-3 py-3 text-sm outline-none focus:border-[#2563eb]" name="email" placeholder="harshdeep@example.com" type="email" /></label><label className="mt-4 block text-xs font-extrabold">Initial password<input required minLength={12} autoComplete="new-password" className="mt-1.5 w-full rounded-xl border border-[#dceaff] px-3 py-3 text-sm outline-none focus:border-[#2563eb]" name="password" type="password" /></label><label className="mt-4 block text-xs font-extrabold">Confirm initial password<input required minLength={12} autoComplete="new-password" className="mt-1.5 w-full rounded-xl border border-[#dceaff] px-3 py-3 text-sm outline-none focus:border-[#2563eb]" name="confirm_password" type="password" /></label>{state.error && <p className="mt-4 rounded-xl bg-[#fff0f1] p-3 text-xs font-bold text-[#a83848]">{state.error}</p>}{state.success && <p className="mt-4 rounded-xl bg-[#e7f7c5] p-3 text-xs font-bold text-[#4f6d1e]">{state.success}</p>}<button disabled={pending} className="mt-5 rounded-xl bg-[#2563eb] px-4 py-3 text-sm font-extrabold text-white disabled:opacity-60">{pending ? "Creating…" : "Create super-admin account"}</button></form>;
}
