// Header strings must match the source workbooks exactly (including the source's own
// "Refernce Number" typo on the sales sheet) — confirmed against real GymMaster exports
// (Customers_CSV_EXPORT_20260829-142027.xlsx, CSV_EXPORT_20260830-162847.xlsx).
export const CUSTOMER_COLUMNS = {
  code: "Code",
  name: "Name",
  isdCode: "ISD Code",
  number: "Number",
  email: "Email",
  gender: "Gender",
  dateOfEnquiry: "Date of Enquiry",
  conversionDate: "Conversion Date",
  handledBy: "Handled By",
  notes: "Notes",
  leadType: "Lead Type",
  sourceOfPromo: "Source of Promo",
  employmentType: "Employment Type",
  appInstalled: "App Installed",
  assignedTrainer: "Assigned Trainer",
  membershipStatus: "Membership Status",
  dob: "DOB",
  address: "Address",
  emergencyContactNo: "Emergency Contact No",
  whatsappNumbers: "WhatsApp Numbers",
  referenceNo: "Reference No",
} as const;

export const SALE_COLUMNS = {
  invoiceNo: "Invoice No",
  invoiceDate: "Invoice Date",
  customerId: "Customer ID",
  customerName: "Customer Name",
  customerEmail: "Customer Email",
  customerPhone: "Customer Phone No.",
  customerAlternatePhone: "Customer Alternate Phone No.",
  planName: "Plan Name",
  startDate: "Start Date",
  endDate: "End Date",
  planStatus: "Plan Status",
  netSaleAmount: "Net Sale Amount",
  gst: "GST",
  totalSaleAmount: "Total Sale Amount",
  paymentStatus: "Payment Status",
  trainerName: "Trainer Name",
  trainerId: "Trainer ID",
  paymentType: "Payment Type",
  staffName: "Staff Name",
  staffId: "Staff ID",
  sourceOfPromotion: "Source Of Promotion",
  paidAmount: "Paid Amount",
  referenceNumber: "Refernce Number",
  note: "Note",
} as const;
