"use client";
import Link from "next/link";
import { useState } from "react";
import { supabase } from "@/lib/supabase/client";
import { normalizeToE164 } from "@/lib/whatsapp/phone";

export default function MemberLoginPage() {
  const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  async function login(form: FormData) { setPending(true); setError(""); const phone = normalizeToE164(String(form.get("phone") ?? "")); if (!phone) { setPending(false); setError("Enter a valid mobile number."); return; } const { error: loginError } = await supabase.auth.signInWithPassword({ phone, password: String(form.get("password") ?? "") }); setPending(false); if (loginError) setError("The mobile number or password is incorrect."); else window.location.assign("/member/dashboard"); }
  return <main className="min-h-screen bg-[#f7fbff] px-5 py-10 text-[#10264a]"><div className="mx-auto max-w-sm"><p className="inline-flex items-center gap-2 text-sm font-extrabold text-[#2563eb]"><span className="grid size-8 place-items-center rounded-xl bg-[#2563eb] text-white">✦</span> BODY &amp; SOUL</p><h1 className="mt-12 font-display text-3xl font-black tracking-[-.05em]">Your fitness space.</h1><p className="mt-2 text-sm font-medium text-[#6980a5]">Sign in to view your QR pass, visits, and membership.</p><form action={login} className="mt-8 space-y-4 rounded-3xl border border-[#dceaff] bg-white p-5 shadow-[0_12px_35px_rgba(37,99,235,.06)]"><label className="block text-xs font-extrabold">Registered mobile number<input required className="mt-1.5 w-full rounded-xl border border-[#dceaff] px-3 py-3 text-sm font-medium outline-none focus:border-[#2563eb]" name="phone" placeholder="+91 98765 43210" type="tel" /></label><label className="block text-xs font-extrabold">Password<input required className="mt-1.5 w-full rounded-xl border border-[#dceaff] px-3 py-3 text-sm font-medium outline-none focus:border-[#2563eb]" name="password" type="password" /></label>{error && <p className="rounded-xl bg-[#fff0f1] p-3 text-xs font-bold text-[#a83848]">{error}</p>}<button disabled={pending} className="w-full rounded-xl bg-[#2563eb] py-3 text-sm font-extrabold text-white disabled:opacity-60">{pending ? "Signing in…" : "Sign in"}</button></form><p className="mt-5 text-center text-sm font-medium text-[#6980a5]">First time or reset by reception? <Link className="font-extrabold text-[#2563eb]" href="/member/activate">Set up access</Link></p></div></main>;
}
