"use client";
import Link from "next/link";
import { useState } from "react";
import { supabase } from "@/lib/supabase/client";
import { normalizeToE164 } from "@/lib/whatsapp/phone";
import HCaptchaField from "@/components/hcaptcha-field";

const CAPTCHA_ENABLED = Boolean(process.env.NEXT_PUBLIC_HCAPTCHA_SITE_KEY);

export default function MemberLoginPage() {
  const [error, setError] = useState(""); const [pending, setPending] = useState(false); const [captchaToken, setCaptchaToken] = useState("");
  async function login(form: FormData) { setPending(true); setError(""); const phone = normalizeToE164(String(form.get("phone") ?? "")); if (!phone) { setPending(false); setError("Enter a valid mobile number."); return; } if (CAPTCHA_ENABLED && !captchaToken) { setPending(false); setError("Complete the security verification before signing in."); return; } try { const response = await fetch("/api/member/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ phone, password: String(form.get("password") ?? ""), captchaToken }) }); const result = await response.json(); if (!response.ok || !result.session) { setError(result.error ?? "We could not sign you in right now. Please try again or contact reception."); setCaptchaToken(""); window.hcaptcha?.reset(); return; } const { error: sessionError } = await supabase.auth.setSession(result.session); if (sessionError) { setError("Your sign-in was accepted but the session could not be started. Please try again."); return; } window.location.assign("/member/dashboard"); } catch { setError("We could not sign you in right now. Please try again or contact reception."); } finally { setPending(false); } }
  return <main className="min-h-screen bg-[#f7fbff] px-5 py-10 text-[#10264a]"><div className="mx-auto max-w-sm"><p className="inline-flex items-center gap-2 text-sm font-extrabold text-[#2563eb]"><span className="grid size-8 place-items-center rounded-xl bg-[#2563eb] text-white">✦</span> BODY &amp; SOUL</p><h1 className="mt-12 font-display text-3xl font-black tracking-[-.05em]">Your fitness space.</h1><p className="mt-2 text-sm font-medium text-[#6980a5]">Sign in to view your QR pass, visits, and membership.</p><form action={login} className="mt-8 space-y-4 rounded-3xl border border-[#dceaff] bg-white p-5 shadow-[0_12px_35px_rgba(37,99,235,.06)]"><label className="block text-xs font-extrabold">Registered mobile number<input required className="mt-1.5 w-full rounded-xl border border-[#dceaff] px-3 py-3 text-sm font-medium outline-none focus:border-[#2563eb]" name="phone" placeholder="+91 98765 43210" type="tel" /></label><label className="block text-xs font-extrabold">Password<input required className="mt-1.5 w-full rounded-xl border border-[#dceaff] px-3 py-3 text-sm font-medium outline-none focus:border-[#2563eb]" name="password" type="password" /></label><HCaptchaField onToken={setCaptchaToken} />{error && <p className="rounded-xl bg-[#fff0f1] p-3 text-xs font-bold text-[#a83848]">{error}</p>}<button disabled={pending} className="w-full rounded-xl bg-[#2563eb] py-3 text-sm font-extrabold text-white disabled:opacity-60">{pending ? "Signing in…" : "Sign in"}</button></form><p className="mt-5 text-center text-sm font-medium text-[#6980a5]">First time or reset by reception? <Link className="font-extrabold text-[#2563eb]" href="/member/activate">Set up access</Link></p></div></main>;
}
