import Link from "next/link";
import { Download, Filter, Settings2, UsersRound } from "lucide-react";
import { supabaseAdmin } from "@/lib/supabase/server";
import { AttendanceConsole } from "./attendance-console";
import { updateAttendancePolicy } from "./actions";
import type { AttendanceSettings } from "@/lib/attendance/types";

function dayStart(date: string) { return `${date}T00:00:00.000Z`; }
function dayEnd(date: string) { return `${date}T23:59:59.999Z`; }
function duration(checkedIn: string, checkedOut: string | null, saved: number | null) { if (saved !== null) return `${saved} min`; if (!checkedOut) return "Inside"; return `${Math.max(0, Math.round((new Date(checkedOut).getTime() - new Date(checkedIn).getTime()) / 60000))} min`; }

export default async function AttendancePage({ searchParams }: { searchParams: Promise<{ date?: string; member?: string; status?: string }> }) {
  const params = await searchParams; const date = params.date || new Date().toISOString().slice(0, 10); const status = params.status || "all"; const member = params.member?.trim() || "";
  let visitQuery = supabaseAdmin.from("member_checkins").select("id,member_id,checked_in_at,checked_out_at,method,checkin_staff,checkout_staff,duration_minutes,members!inner(member_id,full_name,mobile_number)").gte("checked_in_at", dayStart(date)).lte("checked_in_at", dayEnd(date)).order("checked_in_at", { ascending: false }).limit(500);
  if (status === "inside") visitQuery = visitQuery.is("checked_out_at", null); if (status === "completed") visitQuery = visitQuery.not("checked_out_at", "is", null); if (member) visitQuery = visitQuery.or(`member_id.ilike.%${member.replace(/[,%]/g, "")}% ,full_name.ilike.%${member.replace(/[,%]/g, "")}%`, { referencedTable: "members" });
  const [{ data: visits }, { data: allVisits }, { data: policy }] = await Promise.all([visitQuery, supabaseAdmin.from("member_checkins").select("member_id,checked_in_at,checked_out_at,duration_minutes,members!inner(member_id,full_name)").order("checked_in_at", { ascending: false }).limit(2000), supabaseAdmin.from("attendance_settings").select("block_expired,block_suspended,block_inactive").eq("id", true).maybeSingle()]);
  const todayVisits = (visits ?? []) as unknown as Array<{ id: string; member_id: string; checked_in_at: string; checked_out_at: string | null; method: string; checkin_staff: string | null; checkout_staff: string | null; duration_minutes: number | null; members: Array<{ member_id: string; full_name: string }> }>;
  const totalByMember = new Map<string, number>(); (allVisits ?? []).forEach((v: { member_id: string }) => totalByMember.set(v.member_id, (totalByMember.get(v.member_id) ?? 0) + 1));
  const inside = todayVisits.filter(v => !v.checked_out_at).length;
  return <div className="min-h-[calc(100vh-82px)] bg-[#f7fbff] px-5 py-8 sm:px-8 lg:px-10 lg:py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#2563eb]">Live attendance</p><h1 className="mt-2 font-display text-3xl font-black tracking-[-.055em]">Check-in & check-out</h1><p className="mt-2 text-sm font-medium text-[#6980a5]">Use the camera scanner or identify a member manually.</p></div><Link className="inline-flex items-center gap-2 rounded-xl border border-[#dceaff] bg-white px-4 py-3 text-sm font-extrabold text-[#2563eb]" href={`/attendance/export?date=${date}&status=${status}&member=${encodeURIComponent(member)}`}><Download size={16} /> Export CSV</Link></div>
    <div className="mt-7 grid gap-5 xl:grid-cols-[.85fr_1.4fr]"><div className="space-y-5"><AttendanceConsole /><section className="rounded-3xl border border-[#dceaff] bg-white p-5"><div className="flex items-center gap-2 text-sm font-extrabold"><Settings2 size={17} className="text-[#2563eb]" /> Entry policy</div><form action={updateAttendancePolicy} className="mt-4 space-y-3 text-sm font-semibold text-[#526d98]"><label className="flex items-center justify-between gap-3">Block expired subscriptions <input defaultChecked={(policy as AttendanceSettings | null)?.block_expired ?? true} name="block_expired" type="checkbox" /></label><label className="flex items-center justify-between gap-3">Block suspended members <input defaultChecked={(policy as AttendanceSettings | null)?.block_suspended ?? true} name="block_suspended" type="checkbox" /></label><label className="flex items-center justify-between gap-3">Block inactive/frozen members <input defaultChecked={(policy as AttendanceSettings | null)?.block_inactive ?? true} name="block_inactive" type="checkbox" /></label><button className="w-full rounded-xl bg-[#10264a] py-2.5 text-xs font-extrabold text-white">Save policy</button></form></section></div>
      <section className="rounded-3xl border border-[#dceaff] bg-white p-5 shadow-[0_12px_35px_rgba(37,99,235,.05)] sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-extrabold">Visits & active check-ins</p><p className="mt-1 text-xs font-medium text-[#6980a5]">{inside} member{inside === 1 ? "" : "s"} currently inside for this day.</p></div><span className="inline-flex items-center gap-1 rounded-full bg-[#e3efff] px-2.5 py-1 text-xs font-extrabold text-[#2563eb]"><UsersRound size={14} /> {todayVisits.length} visits</span></div><form className="mt-5 grid gap-2 sm:grid-cols-[1fr_1.4fr_1fr_auto]"><input name="date" defaultValue={date} type="date" className="rounded-xl border border-[#dceaff] px-3 py-2.5 text-sm" /><input name="member" defaultValue={member} placeholder="Member name or ID" className="rounded-xl border border-[#dceaff] px-3 py-2.5 text-sm" /><select name="status" defaultValue={status} className="rounded-xl border border-[#dceaff] px-3 py-2.5 text-sm"><option value="all">All statuses</option><option value="inside">Currently inside</option><option value="completed">Checked out</option></select><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#2563eb] px-4 py-2.5 text-sm font-extrabold text-white"><Filter size={15} /> Filter</button></form><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b border-[#e7effb] text-xs font-extrabold uppercase tracking-wide text-[#8990aa]"><th className="pb-3 pr-4">Member</th><th className="pb-3 pr-4">Check-in</th><th className="pb-3 pr-4">Check-out</th><th className="pb-3 pr-4">Duration</th><th className="pb-3 pr-4">Method</th><th className="pb-3">Total visits</th></tr></thead><tbody>{todayVisits.length === 0 ? <tr><td className="py-10 text-center text-sm text-[#6980a5]" colSpan={6}>No visits match these filters.</td></tr> : todayVisits.map(v => <tr className="border-b border-[#edf2fa] last:border-0" key={v.id}><td className="py-3 pr-4"><p className="font-extrabold">{v.members[0]?.full_name ?? "Unknown member"}</p><p className="text-xs font-bold text-[#699238]">{v.members[0]?.member_id ?? "—"}</p></td><td className="py-3 pr-4">{new Date(v.checked_in_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</td><td className="py-3 pr-4">{v.checked_out_at ? new Date(v.checked_out_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : <span className="rounded-full bg-[#e7f7c5] px-2 py-1 text-xs font-extrabold text-[#4f6d1e]">Inside</span>}</td><td className="py-3 pr-4">{duration(v.checked_in_at, v.checked_out_at, v.duration_minutes)}</td><td className="py-3 pr-4 capitalize">{v.method}</td><td className="py-3 font-extrabold">{totalByMember.get(v.member_id) ?? 0}</td></tr>)}</tbody></table></div></section></div></div>;
}
