"use client";

import { useMemo, useState } from "react";
import { ArrowUpRight, CalendarDays, ChevronRight, CircleDollarSign, Clock3, Users, X } from "lucide-react";
import type { ReportType } from "@/lib/reports/data";

type Row = Record<string, unknown>;
type Detail = { title: string; description: string; rows: Row[] };
type Metric = { label: string; value: string; hint: string; rows: Row[]; tone?: "lime" | "orange" | "ink" };
type Bar = { label: string; value: number; rows: Row[] };

const number = (value: number) => new Intl.NumberFormat("en-IN").format(value);
const currency = (value: number, code = "INR") => new Intl.NumberFormat("en-IN", { style: "currency", currency: code, maximumFractionDigits: 0 }).format(value);
const dateLabel = (value: string) => new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short" }).format(new Date(`${value.slice(0, 10)}T00:00:00`));
const clean = (value: unknown) => value === null || value === undefined || value === "" ? "—" : String(value);

function group(rows: Row[], key: (row: Row) => string) {
  const values = new Map<string, Row[]>();
  rows.forEach((row) => { const label = key(row); values.set(label, [...(values.get(label) ?? []), row]); });
  return Array.from(values, ([label, items]) => ({ label, value: items.length, rows: items }));
}

function Chart({ title, subtitle, bars, onSelect, money = false }: { title: string; subtitle: string; bars: Bar[]; onSelect: (detail: Detail) => void; money?: boolean }) {
  const max = Math.max(...bars.map((bar) => bar.value), 1);
  return <section className="rounded-3xl border border-[#e5e9e5] bg-white p-5"><div className="mb-5"><h2 className="font-display text-lg font-black">{title}</h2><p className="mt-1 text-xs font-medium text-[#6c7773]">{subtitle}</p></div>{bars.length ? <div className="flex h-52 items-end gap-2" role="list" aria-label={title}>{bars.map((bar) => <button key={bar.label} onClick={() => onSelect({ title: `${bar.label}: ${money ? currency(bar.value) : number(bar.value)}`, description: `Records included in ${bar.label}.`, rows: bar.rows })} className="group flex h-full min-w-0 flex-1 flex-col justify-end rounded-lg text-left outline-none focus-visible:ring-2 focus-visible:ring-[#699238]" aria-label={`${bar.label}: ${money ? currency(bar.value) : number(bar.value)}. Show details`}><span className="mb-2 text-center text-[11px] font-extrabold text-[#52605b] opacity-0 transition group-hover:opacity-100 group-focus:opacity-100">{money ? currency(bar.value) : number(bar.value)}</span><span className="rounded-t-lg bg-[#a8d546] transition group-hover:bg-[#699238]" style={{ height: `${Math.max((bar.value / max) * 100, 4)}%` }}/><span className="mt-2 truncate text-center text-[10px] font-bold text-[#6c7773]">{bar.label}</span></button>)}</div> : <EmptyChart />}</section>;
}

function Breakdown({ title, bars, onSelect }: { title: string; bars: Bar[]; onSelect: (detail: Detail) => void }) {
  const max = Math.max(...bars.map((bar) => bar.value), 1);
  return <section className="rounded-3xl border border-[#e5e9e5] bg-white p-5"><h2 className="font-display text-lg font-black">{title}</h2><div className="mt-5 space-y-3">{bars.length ? bars.slice(0, 6).map((bar) => <button key={bar.label} onClick={() => onSelect({ title: `${bar.label}: ${number(bar.value)}`, description: `Records included in ${bar.label}.`, rows: bar.rows })} className="group grid w-full grid-cols-[minmax(92px,1fr)_3fr_auto] items-center gap-3 text-left outline-none focus-visible:ring-2 focus-visible:ring-[#699238]"><span className="truncate text-sm font-bold text-[#3a4542]">{bar.label}</span><span className="h-2 overflow-hidden rounded-full bg-[#eef1ed]"><span className="block h-full rounded-full bg-[#111c19] transition group-hover:bg-[#699238]" style={{ width: `${(bar.value / max) * 100}%` }}/></span><span className="text-sm font-black">{number(bar.value)}</span></button>) : <EmptyChart />}</div></section>;
}

function EmptyChart() { return <p className="grid h-40 place-items-center rounded-2xl bg-[#f7f9f6] text-center text-sm font-medium text-[#6c7773]">No activity in this period.</p>; }

function DetailDrawer({ detail, close }: { detail: Detail; close: () => void }) {
  if (!detail) return null;
  return <div className="fixed inset-0 z-50 flex justify-end bg-[#0f1816]/30 p-0 sm:p-4" role="presentation" onMouseDown={close}><aside className="h-full w-full max-w-xl overflow-y-auto rounded-none bg-white shadow-2xl sm:rounded-3xl" role="dialog" aria-modal="true" aria-labelledby="report-detail-title" onMouseDown={(event) => event.stopPropagation()}><div className="sticky top-0 z-10 flex items-start justify-between border-b border-[#e5e9e5] bg-white p-5"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#699238]">Drill down</p><h2 id="report-detail-title" className="font-display mt-1 text-2xl font-black">{detail.title}</h2><p className="mt-1 text-sm text-[#6c7773]">{detail.description}</p></div><button onClick={close} aria-label="Close details" className="rounded-xl p-2 text-[#52605b] hover:bg-[#f3f5f2]"><X size={20}/></button></div><div className="space-y-3 p-5">{detail.rows.length ? detail.rows.slice(0, 100).map((row, index) => <RecordCard key={`${index}-${clean(row.member_id ?? row.mobile_number ?? row.invoice ?? row.full_name)}`} row={row}/>) : <p className="rounded-2xl bg-[#f7f9f6] p-6 text-sm text-[#6c7773]">No matching records.</p>}{detail.rows.length > 100 ? <p className="text-center text-xs font-bold text-[#6c7773]">Showing the first 100 matching records. Export the selected report for the full set.</p> : null}</div></aside></div>;
}

function RecordCard({ row }: { row: Row }) {
  const name = clean(row.member ?? row.full_name ?? row.invoice ?? row.member_id ?? "Record");
  const phone = row.mobile ?? row.mobile_number;
  const entries = Object.entries(row).filter(([key, value]) => !["member", "full_name", "mobile", "mobile_number"].includes(key) && value !== null && value !== undefined).slice(0, 4);
  return <article className="rounded-2xl border border-[#e5e9e5] p-4"><div className="flex items-start justify-between gap-4"><div><h3 className="font-display font-black text-[#17221f]">{name}</h3>{phone ? <p className="mt-1 text-sm font-medium text-[#6c7773]">{clean(phone)}</p> : null}</div>{phone ? <div className="flex gap-1"><a href={`tel:${String(phone).replace(/\D/g, "")}`} className="rounded-lg bg-[#f2f5ef] px-2 py-1 text-xs font-extrabold text-[#17221f]">Call</a><a target="_blank" rel="noreferrer" href={`https://wa.me/${String(phone).replace(/\D/g, "")}`} className="rounded-lg bg-[#e6f4d8] px-2 py-1 text-xs font-extrabold text-[#356313]">WhatsApp</a></div> : null}</div><dl className="mt-3 grid grid-cols-2 gap-x-4 gap-y-2">{entries.map(([key, value]) => <div key={key}><dt className="text-[10px] font-extrabold uppercase tracking-wide text-[#89938f]">{key.replace(/_/g, " ")}</dt><dd className="mt-0.5 truncate text-sm font-bold text-[#3a4542]">{clean(value)}</dd></div>)}</dl></article>;
}

export function ReportDashboard({ type, rows, from, to }: { type: ReportType; rows: Row[]; from: string; to: string }) {
  const [detail, setDetail] = useState<Detail | null>(null);
  const visual = useMemo(() => {
    const byDate = (key: string) => {
      const values = new Map<string, Row[]>();
      rows.forEach((row) => {
        const date = clean(row[key]).slice(0, 10);
        values.set(date, [...(values.get(date) ?? []), row]);
      });
      return Array.from(values)
        .sort(([left], [right]) => left.localeCompare(right))
        .slice(-14)
        .map(([date, items]) => ({ label: dateLabel(date), value: items.length, rows: items }));
    };
    const by = (key: string) => group(rows, (row) => clean(row[key] ?? "Unknown")).sort((a, b) => b.value - a.value);
    const total = rows.length;
    let metrics: Metric[] = []; let primary: Bar[] = []; let secondary: Bar[] = []; let chartTitle = "Activity over time"; let breakdownTitle = "Breakdown";
    switch (type) {
      case "enquiries": metrics = [{ label: "New enquiries", value: number(total), hint: "in this period", rows }, { label: "Open leads", value: number(rows.filter((r) => r.status === "open").length), hint: "need follow-up", rows: rows.filter((r) => r.status === "open"), tone: "orange" }, { label: "Converted", value: number(rows.filter((r) => r.status === "converted").length), hint: "successful leads", rows: rows.filter((r) => r.status === "converted"), tone: "lime" }]; primary = byDate("enquiry_date"); secondary = by("source"); breakdownTitle = "Enquiries by source"; break;
      case "conversion": { const converted = rows.filter((r) => r.status === "converted"); metrics = [{ label: "Total leads", value: number(total), hint: "in this period", rows }, { label: "Converted", value: number(converted.length), hint: "became members", rows: converted, tone: "lime" }, { label: "Conversion rate", value: `${total ? ((converted.length / total) * 100).toFixed(1) : 0}%`, hint: "of all leads", rows: converted, tone: "ink" }]; primary = byDate("enquiry_date"); secondary = by("source"); chartTitle = "Leads received over time"; breakdownTitle = "Lead source quality"; break; }
      case "registrations": metrics = [{ label: "New members", value: number(total), hint: "joined this period", rows }, { label: "Active", value: number(rows.filter((r) => r.status === "active").length), hint: "currently active", rows: rows.filter((r) => r.status === "active"), tone: "lime" }, { label: "Inactive", value: number(rows.filter((r) => r.status !== "active").length), hint: "need attention", rows: rows.filter((r) => r.status !== "active"), tone: "orange" }]; primary = byDate("join_date"); secondary = by("status"); breakdownTitle = "Registration status"; break;
      case "memberships": metrics = [{ label: "Total members", value: number(total), hint: "current member base", rows }, { label: "Active", value: number(rows.filter((r) => r.status === "active").length), hint: "currently active", rows: rows.filter((r) => r.status === "active"), tone: "lime" }, { label: "Other status", value: number(rows.filter((r) => r.status !== "active").length), hint: "review required", rows: rows.filter((r) => r.status !== "active"), tone: "orange" }]; primary = byDate("join_date"); secondary = by("status"); chartTitle = "Member growth"; breakdownTitle = "Membership status"; break;
      case "expiring": metrics = [{ label: "Expiring in 7 days", value: number(total), hint: "active subscriptions", rows, tone: "orange" }, { label: "Due today", value: number(rows.filter((r) => Number(r.days_remaining) === 0).length), hint: "contact now", rows: rows.filter((r) => Number(r.days_remaining) === 0), tone: "orange" }, { label: "Within 3 days", value: number(rows.filter((r) => Number(r.days_remaining) <= 3).length), hint: "high priority", rows: rows.filter((r) => Number(r.days_remaining) <= 3), tone: "lime" }]; primary = group(rows, (r) => `${r.days_remaining} days`).sort((a, b) => Number(a.label) - Number(b.label)); secondary = by("plan"); chartTitle = "Subscription expiry timeline"; breakdownTitle = "Expiring by plan"; break;
      case "revenue": { const amount = (set: Row[]) => set.reduce((sum, r) => sum + Number(r.amount ?? 0), 0); const paymentBars = group(rows, (r) => clean(r.date)).sort((a, b) => a.label.localeCompare(b.label)).slice(-14).map((item) => ({ ...item, label: dateLabel(item.label), value: amount(item.rows) })); metrics = [{ label: "Revenue", value: currency(amount(rows)), hint: "received in this period", rows, tone: "lime" }, { label: "Payments", value: number(total), hint: "transactions", rows }, { label: "Average payment", value: currency(total ? amount(rows) / total : 0), hint: "per transaction", rows }]; primary = paymentBars; secondary = group(rows, (r) => clean(r.payment_mode)).map((item) => ({ ...item, value: amount(item.rows) })).sort((a, b) => b.value - a.value); chartTitle = "Revenue received over time"; breakdownTitle = "Revenue by payment method"; break; }
      case "balances": { const amount = (set: Row[]) => set.reduce((sum, r) => sum + Number(r.outstanding ?? 0), 0); metrics = [{ label: "Outstanding", value: currency(amount(rows)), hint: "amount still due", rows, tone: "orange" }, { label: "Unpaid invoices", value: number(total), hint: "need collection", rows }, { label: "Largest balance", value: currency(Math.max(0, ...rows.map((r) => Number(r.outstanding ?? 0)))), hint: "single invoice", rows: rows.filter((r) => Number(r.outstanding ?? 0) === Math.max(0, ...rows.map((item) => Number(item.outstanding ?? 0)))) }]; primary = [...rows].sort((a, b) => Number(b.outstanding) - Number(a.outstanding)).slice(0, 10).map((r) => ({ label: clean(r.member), value: Number(r.outstanding), rows: [r] })); secondary = by("status"); chartTitle = "Largest outstanding balances"; breakdownTitle = "Invoice status"; break; }
      case "attendance": metrics = [{ label: "Check-ins", value: number(total), hint: "in this period", rows }, { label: "Unique visitors", value: number(new Set(rows.map((r) => r.member_id)).size), hint: "members who attended", rows }, { label: "Average duration", value: `${Math.round(rows.reduce((sum, r) => sum + Number(r.duration_minutes ?? 0), 0) / Math.max(total, 1))} min`, hint: "where checked out", rows }]; primary = byDate("check_in"); secondary = by("method"); chartTitle = "Check-ins over time"; breakdownTitle = "Check-in method"; break;
      case "visitors": metrics = [{ label: "Unique visitors", value: number(total), hint: "in this period", rows }, { label: "Total visits", value: number(rows.reduce((sum, r) => sum + Number(r.visits ?? 0), 0)), hint: "across all members", rows }, { label: "Top visitor", value: number(Math.max(0, ...rows.map((r) => Number(r.visits ?? 0)))), hint: "visits", rows: rows.filter((r) => Number(r.visits ?? 0) === Math.max(0, ...rows.map((item) => Number(item.visits ?? 0)))) }]; primary = rows.slice(0, 10).map((r) => ({ label: clean(r.member), value: Number(r.visits), rows: [r] })); secondary = group(rows, (r) => Number(r.visits) >= 9 ? "9+ visits" : Number(r.visits) >= 5 ? "5–8 visits" : Number(r.visits) >= 2 ? "2–4 visits" : "1 visit"); chartTitle = "Top 10 visitors"; breakdownTitle = "Visit frequency"; break;
    }
    return { metrics, primary, secondary, chartTitle, breakdownTitle };
  }, [rows, type]);
  const icon = type === "revenue" || type === "balances" ? <CircleDollarSign size={18}/> : type === "attendance" || type === "visitors" ? <Users size={18}/> : <CalendarDays size={18}/>;
  return <div className="mt-5 space-y-5"><section className="rounded-3xl border border-[#e5e9e5] bg-[#111c19] p-5 text-white"><div className="flex items-center gap-2 text-[#c9f36a]">{icon}<span className="text-xs font-extrabold uppercase tracking-[.15em]">Interactive overview</span></div><div className="mt-3 flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-display text-2xl font-black">Your report at a glance</h2><p className="mt-1 text-sm text-[#c4ccc8]">{dateLabel(from)} – {dateLabel(to)} · Click any card or chart to see the people and records behind it.</p></div><span className="inline-flex items-center gap-1 text-xs font-bold text-[#c9f36a]">Explore data <ChevronRight size={14}/></span></div></section><div className="grid gap-3 sm:grid-cols-3">{visual.metrics.map((metric) => <button key={metric.label} onClick={() => setDetail({ title: metric.label, description: metric.hint, rows: metric.rows })} className="group rounded-3xl border border-[#e5e9e5] bg-white p-5 text-left outline-none transition hover:-translate-y-0.5 hover:border-[#699238] hover:shadow-lg focus-visible:ring-2 focus-visible:ring-[#699238]"><div className="flex items-start justify-between"><p className="text-xs font-extrabold uppercase tracking-[.13em] text-[#6c7773]">{metric.label}</p><ArrowUpRight size={16} className="text-[#89938f] transition group-hover:text-[#699238]"/></div><p className={`font-display mt-3 text-3xl font-black ${metric.tone === "orange" ? "text-[#d55b3d]" : metric.tone === "lime" ? "text-[#56801f]" : "text-[#111c19]"}`}>{metric.value}</p><p className="mt-1 text-sm font-medium text-[#6c7773]">{metric.hint}</p></button>)}</div><div className="grid gap-5 lg:grid-cols-[1.45fr_1fr]"><Chart title={visual.chartTitle} subtitle="Click a bar to explore the matching records." bars={visual.primary} onSelect={setDetail} money={type === "revenue" || type === "balances"}/><Breakdown title={visual.breakdownTitle} bars={visual.secondary} onSelect={setDetail}/></div><p className="flex items-center gap-2 px-1 text-xs font-medium text-[#6c7773]"><Clock3 size={14}/> Visuals reflect the selected date range. Export remains available for the complete filtered data set.</p><DetailDrawer detail={detail!} close={() => setDetail(null)}/></div>;
}
