"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { Bell, CreditCard, DoorOpen, Dumbbell, LayoutDashboard, Menu, Receipt, Search, Settings, Users, UserPlus } from "lucide-react";
import type { LucideIcon } from "lucide-react";

const navigation: Array<{ icon: LucideIcon; label: string; href?: string }> = [
  { icon: LayoutDashboard, label: "Overview", href: "/" }, { icon: Users, label: "Members", href: "/members" }, { icon: UserPlus, label: "Enquiries", href: "/enquiries" }, { icon: CreditCard, label: "Plans & billing", href: "/subscriptions" }, { icon: Receipt, label: "Payments", href: "/payments" }, { icon: DoorOpen, label: "Attendance" }, { icon: Bell, label: "Notifications", href: "/notifications" }, { icon: Settings, label: "Settings", href: "/settings" },
];

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  return <main className="min-h-screen bg-[#f7fbff] text-[#10264a]"><aside className="fixed inset-y-0 left-0 z-20 hidden w-[76px] flex-col items-center border-r border-[#dceaff] bg-white py-5 shadow-[4px_0_24px_rgba(37,99,235,.04)] lg:flex"><Link aria-label="Body & Soul home" className="grid size-11 place-items-center rounded-2xl bg-[#2563eb] text-white shadow-lg shadow-[#2563eb]/20" href="/"><Dumbbell size={21} strokeWidth={2.8} /></Link><nav className="mt-9 flex w-full flex-col items-center gap-2">{navigation.map(({ icon: Icon, label, href }) => { const isActive = href !== undefined && (href === "/" ? pathname === "/" : pathname.startsWith(href)); const className = `grid size-11 place-items-center rounded-xl transition ${isActive ? "bg-[#dceaff] text-[#2563eb] shadow-sm" : "text-[#6980a5] hover:bg-[#f0f6ff] hover:text-[#2563eb]"}`; const content = <><Icon size={20} /><span className="sr-only">{label}</span></>; return href ? <Link aria-label={label} className={className} href={href} key={label} title={label}>{content}</Link> : <button aria-label={label} className={className} disabled key={label} title={label}>{content}</button>; })}</nav><div className="mt-auto flex flex-col items-center gap-4"><button aria-label="Notifications" className="relative grid size-10 place-items-center rounded-xl text-[#6980a5] hover:bg-[#f0f6ff]"><Bell size={19} /><span className="absolute right-2.5 top-2 size-2 rounded-full bg-[#f35d6a]" /></button><div className="grid size-10 place-items-center rounded-full bg-[#10264a] text-sm font-black text-white">H</div></div></aside><section className="lg:ml-[76px]"><header className="flex h-[82px] items-center justify-between border-b border-[#dceaff] bg-white/90 px-5 backdrop-blur-md sm:px-8 lg:px-10"><div className="flex items-center gap-3 lg:hidden"><button aria-label="Open navigation" className="grid size-10 place-items-center rounded-xl border border-[#dceaff] bg-white"><Menu size={20} /></button><div className="grid size-10 place-items-center rounded-xl bg-[#2563eb] text-white"><Dumbbell size={20} /></div></div><div className="hidden max-w-sm flex-1 items-center gap-3 rounded-xl border border-[#dceaff] bg-[#f7fbff] px-4 py-2.5 lg:flex"><Search size={18} className="text-[#6980a5]" /><span className="text-sm font-medium text-[#8aa0bf]">Search members, invoices...</span></div><div className="ml-auto flex items-center gap-3"><button className="rounded-xl bg-[#2563eb] px-4 py-2.5 text-xs font-extrabold text-white shadow-lg shadow-[#2563eb]/15">AI command center</button><div className="hidden h-9 w-px bg-[#dceaff] sm:block" /><div className="hidden sm:block"><p className="text-sm font-extrabold">Harshdeep</p><p className="text-[11px] font-semibold text-[#6980a5]">Administrator</p></div></div></header>{children}</section></main>;
}
