import Link from "next/link";
import { ArrowRight, CalendarDays, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, CreditCard, MessageCircle, Plus, UserPlus } from "lucide-react";
import { requireSuperAdmin } from "@/lib/auth/admin";
import DashboardGreeting from "./dashboard-greeting";
import DashboardLive from "./dashboard-live";
import { dashboardAnalytics } from "@/lib/dashboard/analytics";

export default async function DashboardPage() {
  const [admin, analytics] = await Promise.all([requireSuperAdmin(), dashboardAnalytics()]);
  const maxCheckins = Math.max(...analytics.weeklyCheckins, 1);
  const paymentDue = analytics.outstandingBalance > 0 ? `₹${Math.round(analytics.outstandingBalance).toLocaleString("en-IN")}` : "₹0";

  return <div className="min-h-[calc(100vh-82px)] bg-[#faf9f6] px-5 py-7 sm:px-8 lg:px-10 lg:py-9">
    <div className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end">
      <DashboardGreeting fullName={admin.fullName} />
      <div className="flex flex-wrap items-center gap-3">
        <span className="inline-flex items-center gap-2 rounded-xl border border-[#e3e5e8] bg-white px-4 py-3 text-xs font-bold text-[#4f596b]"><CalendarDays size={16} className="text-[#1d5de8]" /> This week</span>
        <Link className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#10264a] px-5 py-3 text-sm font-extrabold text-white shadow-lg shadow-[#10264a]/15" href="/members/new"><UserPlus size={17} /> Add member</Link>
      </div>
    </div>

    <section className="mt-8 grid gap-5 xl:grid-cols-[minmax(0,1.62fr)_260px_340px]">
      <div className="rounded-3xl border border-[#e4e4e1] bg-white p-5 shadow-[0_10px_28px_rgba(16,38,74,.05)] sm:p-6">
        <div className="flex items-start justify-between gap-4"><div><h2 className="font-display text-lg font-black tracking-[-.03em]">Weekly performance</h2><p className="mt-1 text-xs font-medium text-[#71809a]">Attendance activity from the past seven days</p></div><span className="rounded-lg bg-[#eef4ff] px-3 py-2 text-xs font-extrabold text-[#1d5de8]">Live data</span></div>
        <div className="mt-8 flex h-52 items-end gap-3 sm:gap-5" aria-label="Weekly check-ins chart">{analytics.weeklyCheckins.map((count, index) => <div className="group flex h-full flex-1 flex-col items-center justify-end gap-2" key={analytics.weeklyLabels[index]}><span className="text-xs font-extrabold text-[#10264a] opacity-0 transition group-hover:opacity-100">{count}</span><div className="w-full max-w-12 rounded-t-xl bg-gradient-to-t from-[#195eea] to-[#6e9eff] transition group-hover:from-[#f3a019] group-hover:to-[#ffca63]" style={{ height: `${Math.max(9, Math.round((count / maxCheckins) * 100))}%` }} /><span className="text-[11px] font-bold text-[#71809a]">{analytics.weeklyLabels[index]}</span></div>)}</div>
        <div className="mt-6 flex flex-wrap items-center gap-x-6 gap-y-2 border-t border-[#eef0f3] pt-4 text-xs"><span className="inline-flex items-center gap-2 font-bold text-[#54627a]"><i className="size-2 rounded-full bg-[#1d5de8]" /> Check-ins</span><span className="font-extrabold text-[#10264a]">{analytics.weeklyCheckins.reduce((sum, count) => sum + count, 0)} visits this week</span></div>
      </div>
      <StatCard icon={CheckCircle2} label="Check-ins" value={String(analytics.todayCheckins)} note={`${analytics.membersInside} currently inside`} />
      <div className="rounded-3xl border border-[#e4e4e1] bg-white p-5 shadow-[0_10px_28px_rgba(16,38,74,.05)]"><div className="flex items-center justify-between"><div className="grid size-11 place-items-center rounded-2xl bg-[#fff4dc] text-[#ee9710]"><Clock3 size={21} /></div><Link href="/attendance" className="text-xs font-extrabold text-[#1d5de8]">View all</Link></div><h2 className="mt-5 font-display text-lg font-black">Today&apos;s schedule</h2><div className="mt-4 space-y-3"><Schedule time="08:00" title="Morning check-in" note="Front desk" /><Schedule time="12:30" title="Member follow-ups" note={`${analytics.risk.high} need attention`} /><Schedule time="18:00" title="Evening peak" note="Prepare the floor" /></div></div>
    </section>

    <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_340px]">
      <div className="rounded-3xl border border-[#e4e4e1] bg-white p-5 shadow-[0_10px_28px_rgba(16,38,74,.05)] sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-display text-lg font-black tracking-[-.03em]">Member moments</h2><p className="mt-1 text-xs font-medium text-[#71809a]">The latest signals from your community</p></div><Link href="/members" className="inline-flex items-center gap-1 text-xs font-extrabold text-[#1d5de8]">View members <ArrowRight size={14} /></Link></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Moment initials="IN" title="Members inside" value={String(analytics.membersInside)} description="Currently checked in" accent="blue" /><Moment initials="EX" title="Expiring soon" value={String(analytics.expiringThisWeek)} description="Memberships this week" accent="amber" /><Moment initials="AT" title="Need attention" value={String(analytics.risk.high)} description="Reach out today" accent="rose" /></div></div>
      <div className="rounded-3xl bg-[#10264a] p-5 text-white shadow-[0_16px_35px_rgba(16,38,74,.18)] sm:p-6"><div className="flex items-center justify-between"><div className="grid size-10 place-items-center rounded-xl bg-white/10 text-[#ffd15c]"><CircleDollarSign size={21}/></div><Link href="/payments" className="text-xs font-extrabold text-[#b8d1ff]">Review payments</Link></div><p className="mt-5 text-sm font-bold text-[#b8c8e6]">Payment due</p><p className="mt-1 font-display text-4xl font-black tracking-[-.055em]">{paymentDue}</p><p className="mt-3 text-xs font-medium leading-5 text-[#aec4ed]">Outstanding invoices that need a reminder or payment follow-up.</p><Link href="/payments" className="mt-6 inline-flex items-center gap-2 text-sm font-extrabold text-white">Open payments <ChevronRight size={16} /></Link></div>
    </section>

    <section className="mt-5 rounded-3xl border border-[#e4e4e1] bg-white p-5 shadow-[0_10px_28px_rgba(16,38,74,.05)] sm:p-6"><div><h2 className="font-display text-lg font-black tracking-[-.03em]">Quick actions</h2><p className="mt-1 text-xs font-medium text-[#71809a]">Keep the gym moving without leaving your dashboard.</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><QuickAction href="/members/new" icon={UserPlus} title="Add new member" tone="blue" /><QuickAction href="/payments" icon={CreditCard} title="Record payment" tone="amber" /><QuickAction href="/attendance" icon={CheckCircle2} title="Open attendance" tone="green" /><QuickAction href="/notifications/send" icon={MessageCircle} title="Send message" tone="rose" /></div></section>
    <div className="mt-5"><DashboardLive generatedAt={analytics.generatedAt} /></div>
  </div>;
}

function StatCard({ icon: Icon, label, value, note }: { icon: typeof CheckCircle2; label: string; value: string; note: string }) { return <div className="rounded-3xl border border-[#e4e4e1] bg-white p-5 shadow-[0_10px_28px_rgba(16,38,74,.05)]"><div className="grid size-11 place-items-center rounded-2xl bg-[#eaf1ff] text-[#1d5de8]"><Icon size={21} /></div><p className="mt-6 text-sm font-bold text-[#52617a]">{label}</p><p className="mt-1 font-display text-4xl font-black tracking-[-.055em] text-[#10264a]">{value}</p><p className="mt-3 text-xs font-bold text-[#37865b]">{note}</p></div>; }
function Schedule({ time, title, note }: { time: string; title: string; note: string }) { return <div className="flex items-start gap-3 border-t border-[#eef0f3] pt-3 first:border-0 first:pt-0"><span className="w-10 text-xs font-extrabold text-[#1d5de8]">{time}</span><span className="mt-1.5 size-2 shrink-0 rounded-full bg-[#f0a016]"/><div><p className="text-sm font-extrabold text-[#17223b]">{title}</p><p className="mt-0.5 text-xs font-medium text-[#71809a]">{note}</p></div></div>; }
function Moment({ initials, title, value, description, accent }: { initials: string; title: string; value: string; description: string; accent: "blue" | "amber" | "rose" }) { const tones = { blue: "bg-[#eaf1ff] text-[#1d5de8]", amber: "bg-[#fff4dc] text-[#e68c08]", rose: "bg-[#fff0f2] text-[#dc4c66]" }; return <div className="rounded-2xl border border-[#eaecf0] p-4"><span className={`grid size-10 place-items-center rounded-full text-xs font-black ${tones[accent]}`}>{initials}</span><p className="mt-4 text-xs font-bold text-[#71809a]">{title}</p><p className="mt-1 text-2xl font-black tracking-[-.05em] text-[#10264a]">{value}</p><p className="mt-1 text-xs font-medium text-[#71809a]">{description}</p></div>; }
function QuickAction({ href, icon: Icon, title, tone }: { href: string; icon: typeof Plus; title: string; tone: "blue" | "amber" | "green" | "rose" }) { const tones = { blue: "bg-[#eaf1ff] text-[#1d5de8]", amber: "bg-[#fff4dc] text-[#e68c08]", green: "bg-[#eaf8ef] text-[#29945d]", rose: "bg-[#fff0f2] text-[#dc4c66]" }; return <Link href={href} className="group flex items-center gap-3 rounded-2xl border border-[#e7e9ed] p-4 transition hover:-translate-y-0.5 hover:border-[#cbd5e7] hover:shadow-md"><span className={`grid size-10 place-items-center rounded-xl ${tones[tone]}`}><Icon size={19}/></span><span className="flex-1 text-sm font-extrabold text-[#17223b]">{title}</span><ChevronRight size={17} className="text-[#8a98ae] transition group-hover:translate-x-0.5" /></Link>; }
