import Link from "next/link";
import { ArrowUpRight, Bot, CalendarClock, ChevronRight, DoorOpen, MessageCircle, Timer, UserPlus, Users } from "lucide-react";
import { requireSuperAdmin } from "@/lib/auth/admin";
import DashboardGreeting from "./dashboard-greeting";
import DashboardLive from "./dashboard-live";
import { dashboardAnalytics } from "@/lib/dashboard/analytics";

export default async function DashboardPage() {
  const admin = await requireSuperAdmin();
  const analytics = await dashboardAnalytics();
  return <div className="min-h-[calc(100vh-82px)] bg-[#f7fbff] px-5 py-8 sm:px-8 lg:px-10 lg:py-10">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><DashboardGreeting fullName={admin.fullName} /><Link className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#10264a] px-5 py-3 text-sm font-extrabold text-white shadow-xl shadow-[#10264a]/15" href="/members/new"><UserPlus size={17} /> Add member</Link></div>
    <div className="mt-7"><DashboardLive generatedAt={analytics.generatedAt} /></div>
    <section className="mt-5 rounded-3xl border border-[#dceaff] bg-white p-5 shadow-[0_12px_35px_rgba(37,99,235,.05)] sm:p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-extrabold">Today&apos;s briefing</p><p className="mt-1 text-xs font-medium text-[#6980a5]">Live gym activity and membership signals</p></div><Bot size={20} className="text-[#2563eb]" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={DoorOpen} title="Today’s check-ins" value={String(analytics.todayCheckins)} note="Live attendance" tone="blue" /><Metric icon={Users} title="Members inside" value={String(analytics.membersInside)} note="Currently checked in" tone="indigo" /><Metric icon={Timer} title="Average visit" value={analytics.averageVisitMinutes ? `${analytics.averageVisitMinutes} min` : "—"} note="Completed visits today" tone="orange" /><Metric icon={CalendarClock} title="Expiring this week" value={String(analytics.expiringThisWeek)} note="Take action" tone="rose" /></div></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_.9fr]"><div className="space-y-5"><div className="rounded-3xl border border-[#dceaff] bg-white p-5 shadow-[0_12px_35px_rgba(37,99,235,.05)] sm:p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-extrabold">Membership attention score</p><p className="mt-1 text-xs font-medium text-[#6980a5]">Calculated from recent attendance, upcoming expiry, and unpaid balance</p></div><ChevronRight size={18} className="text-[#6980a5]" /></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Risk label="High attention" value={analytics.risk.high} note="Contact soon" accent="text-[#e34a58] bg-[#fff0f1]" /><Risk label="Medium attention" value={analytics.risk.medium} note="Monitor" accent="text-[#d88b19] bg-[#fff8e8]" /><Risk label="Low attention" value={analytics.risk.low} note="On track" accent="text-[#4a9b4a] bg-[#eefaf0]" /></div></div><div className="rounded-3xl border border-[#dceaff] bg-white p-5 shadow-[0_12px_35px_rgba(37,99,235,.05)] sm:p-6"><div className="flex items-center justify-between"><p className="text-sm font-extrabold">Operational insights</p><span className="text-xs font-bold text-[#2563eb]">Live analysis</span></div><div className="mt-5 grid gap-3 md:grid-cols-3">{analytics.insights.map((insight) => <Insight key={insight.title} {...insight} />)}</div></div></div><aside className="rounded-3xl bg-[#10264a] p-5 text-white shadow-[0_16px_45px_rgba(16,38,74,.18)] sm:p-6"><p className="text-sm font-extrabold">Suggested action</p><p className="mt-2 text-xs leading-5 text-[#aec4ed]">{analytics.suggestedAction?.text ?? "No high-attention members are currently detected."}</p><div className="mt-7 rounded-2xl bg-white p-4 text-[#10264a]"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#e3efff] text-[#2563eb]"><MessageCircle size={20} /></div><div><p className="text-sm font-extrabold">Review before messaging</p><p className="mt-1 text-xs font-medium text-[#6980a5]">WhatsApp outreach stays administrator-approved.</p></div></div></div></aside></section>
  </div>;
}

function Metric({ icon: Icon, title, value, note, tone }: { icon: typeof Users; title: string; value: string; note: string; tone: "blue" | "indigo" | "rose" | "orange" }) { const tones = { blue: "bg-[#e3efff] text-[#2563eb]", indigo: "bg-[#eeecff] text-[#5b59d9]", rose: "bg-[#fff0f3] text-[#e34a58]", orange: "bg-[#fff5e9] text-[#d88b19]" }; return <div className="rounded-2xl border border-[#e7effb] p-4"><div className={`grid size-9 place-items-center rounded-xl ${tones[tone]}`}><Icon size={18} /></div><p className="mt-4 text-xs font-bold text-[#6980a5]">{title}</p><p className="mt-1 text-2xl font-black tracking-[-.05em]">{value}</p><p className="mt-2 text-[11px] font-bold text-[#3d8b56]">{note}</p></div>; }
function Insight({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl bg-[#f7fbff] p-4"><p className="text-xs font-extrabold text-[#2563eb]">{title}</p><p className="mt-2 text-xs font-medium leading-5 text-[#6980a5]">{text}</p></div>; }
function Risk({ label, value, note, accent }: { label: string; value: number; note: string; accent: string }) { return <div className={`rounded-2xl p-4 ${accent}`}><p className="text-xs font-extrabold">{label}</p><p className="mt-3 text-3xl font-black tracking-[-.06em]">{value}</p><p className="mt-1 text-xs font-bold">Members</p><p className="mt-4 text-xs font-extrabold">{note}</p></div>; }
