import Link from "next/link";
import { Download, FileBarChart } from "lucide-react";
import { REPORT_TYPES, reportRows, type ReportType } from "@/lib/reports/data";

const labels: Record<ReportType, string> = { enquiries: "New enquiries", conversion: "Enquiry conversion", registrations: "Member registrations", memberships: "Membership status", expiring: "Expiring subscriptions", revenue: "Revenue", balances: "Outstanding balances", attendance: "Check-in attendance", visitors: "Top visitors" };
type SearchParams = Record<string, string | string[] | undefined>;
const input = "rounded-xl border border-[#e5e9e5] bg-[#f9faf8] px-3 py-2 text-sm font-medium outline-none focus:border-[#111c19]";

export default async function ReportsPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const params = await searchParams; const type = (typeof params.report === "string" && REPORT_TYPES.includes(params.report as ReportType) ? params.report : "enquiries") as ReportType;
  const filters = { from: typeof params.from === "string" ? params.from : undefined, to: typeof params.to === "string" ? params.to : undefined };
  const { rows, error } = await reportRows(type, filters); const columns = Object.keys(rows[0] ?? {});
  const query = new URLSearchParams({ report: type, ...(filters.from ? { from: filters.from } : {}), ...(filters.to ? { to: filters.to } : {}) });
  return <div className="grid-pattern px-5 py-8 sm:px-8 lg:px-10 lg:py-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#699238]">Business intelligence</p><h1 className="font-display mt-2 text-3xl font-black tracking-[-.055em] sm:text-4xl">Reports</h1><p className="mt-2 text-sm font-medium text-[#6c7773]">Filter every report by period and export the displayed data to CSV.</p></div><a href={`/reports/export?${query}`} className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#e5e9e5] bg-white px-4 py-3 text-sm font-extrabold"><Download size={16}/> Export CSV</a></div><form method="get" className="mt-6 flex flex-wrap gap-3 rounded-3xl border border-[#e5e9e5] bg-white p-4"><select className={input} defaultValue={type} name="report">{REPORT_TYPES.map((r) => <option key={r} value={r}>{labels[r]}</option>)}</select><input className={input} defaultValue={filters.from} name="from" aria-label="From date" type="date"/><input className={input} defaultValue={filters.to} name="to" aria-label="To date" type="date"/><button className="rounded-xl bg-[#111c19] px-4 py-2 text-sm font-extrabold text-white">Run report</button></form><section className="mt-5 rounded-3xl border border-[#e5e9e5] bg-white"><div className="flex items-center gap-3 border-b border-[#e5e9e5] px-5 py-4"><FileBarChart className="text-[#699238]" size={19}/><h2 className="font-display text-xl font-black">{labels[type]}</h2><span className="ml-auto text-xs font-bold text-[#89938f]">{rows.length.toLocaleString()} rows</span></div>{error ? <p className="p-6 text-sm font-bold text-[#a94f37]">Could not load this report: {error.message}</p> : !rows.length ? <p className="p-8 text-center text-sm font-medium text-[#6c7773]">No data matches the selected period.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b border-[#e5e9e5] text-xs uppercase tracking-wide text-[#89938f]">{columns.map((c) => <th className="px-5 py-3 font-extrabold" key={c}>{c.replace(/_/g, " ")}</th>)}</tr></thead><tbody>{rows.map((row: any, i) => <tr className="border-b border-[#f0f2f0] last:border-0" key={i}>{columns.map((c) => <td className="px-5 py-3.5 font-medium text-[#3a4542]" key={c}>{row[c] ?? "—"}</td>)}</tr>)}</tbody></table></div>}</section><p className="mt-4 text-xs font-medium text-[#89938f]">Membership status is current state; expiring subscriptions use the next 7 days.</p></div>;
}
