import Link from "next/link";
import { ArrowLeft, UserPlus } from "lucide-react";
import { supabaseAdmin } from "@/lib/supabase/server";
import { saveStaff, toggleStaff } from "./actions";
const input = "mt-1 w-full rounded-xl border border-[#e5e9e5] bg-[#f9faf8] px-3 py-2.5 text-sm outline-none focus:border-[#111c19]";
export default async function StaffSettingsPage() {
 const { data: staff, error } = await supabaseAdmin.from("staff_users").select("*").order("full_name");
 return <div className="grid-pattern px-5 py-8 sm:px-8 lg:px-10"><Link href="/settings" className="inline-flex items-center gap-1 text-sm font-bold text-[#577c25]"><ArrowLeft size={16}/> Settings</Link><h1 className="font-display mt-4 text-3xl font-black">Staff & roles</h1><p className="mt-2 text-sm text-[#6c7773]">Maintain the staff directory and access role assignments. Staff accounts should be provisioned through Supabase Auth before access is granted.</p><div className="mt-6 grid gap-5 xl:grid-cols-[360px_1fr]"><form action={saveStaff} className="rounded-3xl border border-[#e5e9e5] bg-white p-5"><div className="flex items-center gap-2 font-display text-xl font-black"><UserPlus size={19}/> Add staff record</div><label className="mt-5 block text-xs font-extrabold">Full name<input required className={input} name="full_name" maxLength={100}/></label><label className="mt-4 block text-xs font-extrabold">Email<input required className={input} name="email" type="email" maxLength={254}/></label><label className="mt-4 block text-xs font-extrabold">Role<select className={input} name="role"><option value="staff">Staff</option><option value="front_desk">Front desk</option><option value="trainer">Trainer</option><option value="manager">Manager</option><option value="administrator">Administrator</option></select></label><label className="mt-4 flex gap-2 text-sm font-bold"><input defaultChecked name="is_active" type="checkbox"/> Active account</label><button className="mt-5 rounded-xl bg-[#111c19] px-4 py-2.5 text-sm font-extrabold text-white">Save staff</button></form><section className="overflow-x-auto rounded-3xl border border-[#e5e9e5] bg-white">{error ? <p className="p-6 text-sm font-bold text-[#a94f37]">Could not load staff: {error.message}</p> : <table className="w-full min-w-[600px] text-left text-sm"><thead><tr className="border-b border-[#e5e9e5] text-xs uppercase text-[#89938f]"><th className="px-5 py-3">Name</th><th className="px-5 py-3">Email</th><th className="px-5 py-3">Role</th><th className="px-5 py-3">Status</th><th className="px-5 py-3"/></tr></thead><tbody>{(staff ?? []).map((user) => <tr key={user.id} className="border-b border-[#f0f2f0]"><td className="px-5 py-3 font-bold">{user.full_name}</td><td className="px-5 py-3">{user.email}</td><td className="px-5 py-3 capitalize">{user.role.replace("_", " ")}</td><td className="px-5 py-3">{user.is_active ? "Active" : "Disabled"}</td><td className="px-5 py-3"><form action={toggleStaff}><input name="id" type="hidden" value={user.id}/><input name="is_active" type="hidden" value={String(!user.is_active)}/><button className="text-xs font-extrabold text-[#577c25]">{user.is_active ? "Disable" : "Enable"}</button></form></td></tr>)}</tbody></table>}</section></div></div>;
}
